// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: pkg/scheduler/api/devices/nvidia/vgpu/dqngrpc/dqn_scheduler.proto

package dqngrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DQNSchedulerClient is the client API for DQNScheduler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DQNSchedulerClient interface {
	Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictResponse, error)
	ScheduleJob(ctx context.Context, in *ScheduleJobRequest, opts ...grpc.CallOption) (*ScheduleJobResponse, error)
}

type dQNSchedulerClient struct {
	cc grpc.ClientConnInterface
}

func NewDQNSchedulerClient(cc grpc.ClientConnInterface) DQNSchedulerClient {
	return &dQNSchedulerClient{cc}
}

func (c *dQNSchedulerClient) Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictResponse, error) {
	out := new(PredictResponse)
	err := c.cc.Invoke(ctx, "/dqn_scheduler.DQNScheduler/Predict", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dQNSchedulerClient) ScheduleJob(ctx context.Context, in *ScheduleJobRequest, opts ...grpc.CallOption) (*ScheduleJobResponse, error) {
	out := new(ScheduleJobResponse)
	err := c.cc.Invoke(ctx, "/dqn_scheduler.DQNScheduler/ScheduleJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DQNSchedulerServer is the server API for DQNScheduler service.
// All implementations must embed UnimplementedDQNSchedulerServer
// for forward compatibility
type DQNSchedulerServer interface {
	Predict(context.Context, *PredictRequest) (*PredictResponse, error)
	ScheduleJob(context.Context, *ScheduleJobRequest) (*ScheduleJobResponse, error)
	mustEmbedUnimplementedDQNSchedulerServer()
}

// UnimplementedDQNSchedulerServer must be embedded to have forward compatible implementations.
type UnimplementedDQNSchedulerServer struct {
}

func (UnimplementedDQNSchedulerServer) Predict(context.Context, *PredictRequest) (*PredictResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Predict not implemented")
}
func (UnimplementedDQNSchedulerServer) ScheduleJob(context.Context, *ScheduleJobRequest) (*ScheduleJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScheduleJob not implemented")
}
func (UnimplementedDQNSchedulerServer) mustEmbedUnimplementedDQNSchedulerServer() {}

// UnsafeDQNSchedulerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DQNSchedulerServer will
// result in compilation errors.
type UnsafeDQNSchedulerServer interface {
	mustEmbedUnimplementedDQNSchedulerServer()
}

func RegisterDQNSchedulerServer(s grpc.ServiceRegistrar, srv DQNSchedulerServer) {
	s.RegisterService(&DQNScheduler_ServiceDesc, srv)
}

func _DQNScheduler_Predict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DQNSchedulerServer).Predict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dqn_scheduler.DQNScheduler/Predict",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DQNSchedulerServer).Predict(ctx, req.(*PredictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DQNScheduler_ScheduleJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DQNSchedulerServer).ScheduleJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dqn_scheduler.DQNScheduler/ScheduleJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DQNSchedulerServer).ScheduleJob(ctx, req.(*ScheduleJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DQNScheduler_ServiceDesc is the grpc.ServiceDesc for DQNScheduler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DQNScheduler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dqn_scheduler.DQNScheduler",
	HandlerType: (*DQNSchedulerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Predict",
			Handler:    _DQNScheduler_Predict_Handler,
		},
		{
			MethodName: "ScheduleJob",
			Handler:    _DQNScheduler_ScheduleJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/scheduler/api/devices/nvidia/vgpu/dqngrpc/dqn_scheduler.proto",
}
