// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: pkg/scheduler/api/devices/nvidia/vgpu/dqngrpc/dqn_scheduler.proto

package dqngrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GPUState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index      int32  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Uuid       string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	TotalMem   uint32 `protobuf:"varint,3,opt,name=total_mem,json=totalMem,proto3" json:"total_mem,omitempty"`
	UsedMem    uint32 `protobuf:"varint,4,opt,name=used_mem,json=usedMem,proto3" json:"used_mem,omitempty"`
	UsedCore   uint32 `protobuf:"varint,5,opt,name=used_core,json=usedCore,proto3" json:"used_core,omitempty"`
	UsedNum    uint32 `protobuf:"varint,6,opt,name=used_num,json=usedNum,proto3" json:"used_num,omitempty"`
	Number     uint32 `protobuf:"varint,7,opt,name=number,proto3" json:"number,omitempty"`
	DeviceType string `protobuf:"bytes,8,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
}

func (x *GPUState) Reset() {
	*x = GPUState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_scheduler_api_devices_nvidia_vgpu_dqngrpc_dqn_scheduler_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GPUState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUState) ProtoMessage() {}

func (x *GPUState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_scheduler_api_devices_nvidia_vgpu_dqngrpc_dqn_scheduler_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUState.ProtoReflect.Descriptor instead.
func (*GPUState) Descriptor() ([]byte, []int) {
	return file_pkg_scheduler_api_devices_nvidia_vgpu_dqngrpc_dqn_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *GPUState) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *GPUState) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GPUState) GetTotalMem() uint32 {
	if x != nil {
		return x.TotalMem
	}
	return 0
}

func (x *GPUState) GetUsedMem() uint32 {
	if x != nil {
		return x.UsedMem
	}
	return 0
}

func (x *GPUState) GetUsedCore() uint32 {
	if x != nil {
		return x.UsedCore
	}
	return 0
}

func (x *GPUState) GetUsedNum() uint32 {
	if x != nil {
		return x.UsedNum
	}
	return 0
}

func (x *GPUState) GetNumber() uint32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *GPUState) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

type PredictRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeName     string      `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	PodNamespace string      `protobuf:"bytes,2,opt,name=pod_namespace,json=podNamespace,proto3" json:"pod_namespace,omitempty"`
	PodName      string      `protobuf:"bytes,3,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	MemReq       uint32      `protobuf:"varint,4,opt,name=mem_req,json=memReq,proto3" json:"mem_req,omitempty"`
	CoreReq      uint32      `protobuf:"varint,5,opt,name=core_req,json=coreReq,proto3" json:"core_req,omitempty"`
	Nums         int32       `protobuf:"varint,6,opt,name=nums,proto3" json:"nums,omitempty"`
	Gpus         []*GPUState `protobuf:"bytes,7,rep,name=gpus,proto3" json:"gpus,omitempty"`
}

func (x *PredictRequest) Reset() {
	*x = PredictRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_scheduler_api_devices_nvidia_vgpu_dqngrpc_dqn_scheduler_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictRequest) ProtoMessage() {}

func (x *PredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_scheduler_api_devices_nvidia_vgpu_dqngrpc_dqn_scheduler_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictRequest.ProtoReflect.Descriptor instead.
func (*PredictRequest) Descriptor() ([]byte, []int) {
	return file_pkg_scheduler_api_devices_nvidia_vgpu_dqngrpc_dqn_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *PredictRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *PredictRequest) GetPodNamespace() string {
	if x != nil {
		return x.PodNamespace
	}
	return ""
}

func (x *PredictRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *PredictRequest) GetMemReq() uint32 {
	if x != nil {
		return x.MemReq
	}
	return 0
}

func (x *PredictRequest) GetCoreReq() uint32 {
	if x != nil {
		return x.CoreReq
	}
	return 0
}

func (x *PredictRequest) GetNums() int32 {
	if x != nil {
		return x.Nums
	}
	return 0
}

func (x *PredictRequest) GetGpus() []*GPUState {
	if x != nil {
		return x.Gpus
	}
	return nil
}

type GPUScore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index int32   `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Score float64 `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	Fit   bool    `protobuf:"varint,3,opt,name=fit,proto3" json:"fit,omitempty"`
}

func (x *GPUScore) Reset() {
	*x = GPUScore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_scheduler_api_devices_nvidia_vgpu_dqngrpc_dqn_scheduler_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GPUScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUScore) ProtoMessage() {}

func (x *GPUScore) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_scheduler_api_devices_nvidia_vgpu_dqngrpc_dqn_scheduler_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUScore.ProtoReflect.Descriptor instead.
func (*GPUScore) Descriptor() ([]byte, []int) {
	return file_pkg_scheduler_api_devices_nvidia_vgpu_dqngrpc_dqn_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *GPUScore) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *GPUScore) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *GPUScore) GetFit() bool {
	if x != nil {
		return x.Fit
	}
	return false
}

type PredictResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderedIndexes []int32     `protobuf:"varint,1,rep,packed,name=ordered_indexes,json=orderedIndexes,proto3" json:"ordered_indexes,omitempty"`
	SelectedIndex  int32       `protobuf:"varint,2,opt,name=selected_index,json=selectedIndex,proto3" json:"selected_index,omitempty"`
	Scores         []*GPUScore `protobuf:"bytes,3,rep,name=scores,proto3" json:"scores,omitempty"`
	Fallback       bool        `protobuf:"varint,4,opt,name=fallback,proto3" json:"fallback,omitempty"`
	Reason         string      `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *PredictResponse) Reset() {
	*x = PredictResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_scheduler_api_devices_nvidia_vgpu_dqngrpc_dqn_scheduler_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PredictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictResponse) ProtoMessage() {}

func (x *PredictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_scheduler_api_devices_nvidia_vgpu_dqngrpc_dqn_scheduler_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictResponse.ProtoReflect.Descriptor instead.
func (*PredictResponse) Descriptor() ([]byte, []int) {
	return file_pkg_scheduler_api_devices_nvidia_vgpu_dqngrpc_dqn_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *PredictResponse) GetOrderedIndexes() []int32 {
	if x != nil {
		return x.OrderedIndexes
	}
	return nil
}

func (x *PredictResponse) GetSelectedIndex() int32 {
	if x != nil {
		return x.SelectedIndex
	}
	return 0
}

func (x *PredictResponse) GetScores() []*GPUScore {
	if x != nil {
		return x.Scores
	}
	return nil
}

func (x *PredictResponse) GetFallback() bool {
	if x != nil {
		return x.Fallback
	}
	return false
}

func (x *PredictResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_pkg_scheduler_api_devices_nvidia_vgpu_dqngrpc_dqn_scheduler_proto protoreflect.FileDescriptor

var file_pkg_scheduler_api_devices_nvidia_vgpu_dqngrpc_dqn_scheduler_proto_rawDesc = []byte{
	0x0a, 0x41, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x72, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x6e, 0x76, 0x69, 0x64,
	0x69, 0x61, 0x2f, 0x76, 0x67, 0x70, 0x75, 0x2f, 0x64, 0x71, 0x6e, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x64, 0x71, 0x6e, 0x5f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x64, 0x71, 0x6e, 0x5f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c,
	0x65, 0x72, 0x22, 0xdd, 0x01, 0x0a, 0x08, 0x47, 0x50, 0x55, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x5f, 0x6d, 0x65, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x4d, 0x65, 0x6d, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x64, 0x5f, 0x6d,
	0x65, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x75, 0x73, 0x65, 0x64, 0x4d, 0x65,
	0x6d, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x75, 0x73, 0x65, 0x64, 0x43, 0x6f, 0x72, 0x65, 0x12, 0x19,
	0x0a, 0x08, 0x75, 0x73, 0x65, 0x64, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x07, 0x75, 0x73, 0x65, 0x64, 0x4e, 0x75, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x22, 0xe2, 0x01, 0x0a, 0x0e, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x6f, 0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x6f, 0x64, 0x4e, 0x61,
	0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x6f, 0x64, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x6f, 0x64, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x5f, 0x72, 0x65, 0x71, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x63,
	0x6f, 0x72, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x63,
	0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x75, 0x6d, 0x73, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6e, 0x75, 0x6d, 0x73, 0x12, 0x2b, 0x0a, 0x04, 0x67, 0x70,
	0x75, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x64, 0x71, 0x6e, 0x5f, 0x73,
	0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x72, 0x2e, 0x47, 0x50, 0x55, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x04, 0x67, 0x70, 0x75, 0x73, 0x22, 0x48, 0x0a, 0x08, 0x47, 0x50, 0x55, 0x53, 0x63,
	0x6f, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f,
	0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x66, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x66, 0x69,
	0x74, 0x22, 0xc6, 0x01, 0x0a, 0x0f, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x65, 0x64,
	0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0e,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x65, 0x64, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x73, 0x12, 0x25,
	0x0a, 0x0e, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x2f, 0x0a, 0x06, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x64, 0x71, 0x6e, 0x5f, 0x73, 0x63, 0x68, 0x65,
	0x64, 0x75, 0x6c, 0x65, 0x72, 0x2e, 0x47, 0x50, 0x55, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x06,
	0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x61, 0x6c, 0x6c, 0x62, 0x61,
	0x63, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x66, 0x61, 0x6c, 0x6c, 0x62, 0x61,
	0x63, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x32, 0x58, 0x0a, 0x0c, 0x44, 0x51,
	0x4e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x72, 0x12, 0x48, 0x0a, 0x07, 0x50, 0x72,
	0x65, 0x64, 0x69, 0x63, 0x74, 0x12, 0x1d, 0x2e, 0x64, 0x71, 0x6e, 0x5f, 0x73, 0x63, 0x68, 0x65,
	0x64, 0x75, 0x6c, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x64, 0x71, 0x6e, 0x5f, 0x73, 0x63, 0x68, 0x65, 0x64,
	0x75, 0x6c, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x4a, 0x5a, 0x48, 0x76, 0x6f, 0x6c, 0x63, 0x61, 0x6e, 0x6f, 0x2e,
	0x73, 0x68, 0x2f, 0x76, 0x6f, 0x6c, 0x63, 0x61, 0x6e, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x73,
	0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x2f, 0x6e, 0x76, 0x69, 0x64, 0x69, 0x61, 0x2f, 0x76, 0x67, 0x70, 0x75,
	0x2f, 0x64, 0x71, 0x6e, 0x67, 0x72, 0x70, 0x63, 0x3b, 0x64, 0x71, 0x6e, 0x67, 0x72, 0x70, 0x63,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_scheduler_api_devices_nvidia_vgpu_dqngrpc_dqn_scheduler_proto_rawDescOnce sync.Once
	file_pkg_scheduler_api_devices_nvidia_vgpu_dqngrpc_dqn_scheduler_proto_rawDescData = file_pkg_scheduler_api_devices_nvidia_vgpu_dqngrpc_dqn_scheduler_proto_rawDesc
)

func file_pkg_scheduler_api_devices_nvidia_vgpu_dqngrpc_dqn_scheduler_proto_rawDescGZIP() []byte {
	file_pkg_scheduler_api_devices_nvidia_vgpu_dqngrpc_dqn_scheduler_proto_rawDescOnce.Do(func() {
		file_pkg_scheduler_api_devices_nvidia_vgpu_dqngrpc_dqn_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_scheduler_api_devices_nvidia_vgpu_dqngrpc_dqn_scheduler_proto_rawDescData)
	})
	return file_pkg_scheduler_api_devices_nvidia_vgpu_dqngrpc_dqn_scheduler_proto_rawDescData
}

var file_pkg_scheduler_api_devices_nvidia_vgpu_dqngrpc_dqn_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_scheduler_api_devices_nvidia_vgpu_dqngrpc_dqn_scheduler_proto_goTypes = []interface{}{
	(*GPUState)(nil),        // 0: dqn_scheduler.GPUState
	(*PredictRequest)(nil),  // 1: dqn_scheduler.PredictRequest
	(*GPUScore)(nil),        // 2: dqn_scheduler.GPUScore
	(*PredictResponse)(nil), // 3: dqn_scheduler.PredictResponse
}
var file_pkg_scheduler_api_devices_nvidia_vgpu_dqngrpc_dqn_scheduler_proto_depIdxs = []int32{
	0, // 0: dqn_scheduler.PredictRequest.gpus:type_name -> dqn_scheduler.GPUState
	2, // 1: dqn_scheduler.PredictResponse.scores:type_name -> dqn_scheduler.GPUScore
	1, // 2: dqn_scheduler.DQNScheduler.Predict:input_type -> dqn_scheduler.PredictRequest
	3, // 3: dqn_scheduler.DQNScheduler.Predict:output_type -> dqn_scheduler.PredictResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_scheduler_api_devices_nvidia_vgpu_dqngrpc_dqn_scheduler_proto_init() }
func file_pkg_scheduler_api_devices_nvidia_vgpu_dqngrpc_dqn_scheduler_proto_init() {
	if File_pkg_scheduler_api_devices_nvidia_vgpu_dqngrpc_dqn_scheduler_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_scheduler_api_devices_nvidia_vgpu_dqngrpc_dqn_scheduler_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GPUState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_scheduler_api_devices_nvidia_vgpu_dqngrpc_dqn_scheduler_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PredictRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_scheduler_api_devices_nvidia_vgpu_dqngrpc_dqn_scheduler_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GPUScore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_scheduler_api_devices_nvidia_vgpu_dqngrpc_dqn_scheduler_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PredictResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_scheduler_api_devices_nvidia_vgpu_dqngrpc_dqn_scheduler_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_scheduler_api_devices_nvidia_vgpu_dqngrpc_dqn_scheduler_proto_goTypes,
		DependencyIndexes: file_pkg_scheduler_api_devices_nvidia_vgpu_dqngrpc_dqn_scheduler_proto_depIdxs,
		MessageInfos:      file_pkg_scheduler_api_devices_nvidia_vgpu_dqngrpc_dqn_scheduler_proto_msgTypes,
	}.Build()
	File_pkg_scheduler_api_devices_nvidia_vgpu_dqngrpc_dqn_scheduler_proto = out.File
	file_pkg_scheduler_api_devices_nvidia_vgpu_dqngrpc_dqn_scheduler_proto_rawDesc = nil
	file_pkg_scheduler_api_devices_nvidia_vgpu_dqngrpc_dqn_scheduler_proto_goTypes = nil
	file_pkg_scheduler_api_devices_nvidia_vgpu_dqngrpc_dqn_scheduler_proto_depIdxs = nil
}
